[config]
schemaVersion = "0.0.1"

[package]
namespace = "XPRising"
name = "XPRising"
versionNumber = "0.1.11"
description = "Server mod that exchanges item gear level for an XP levelling system"
websiteUrl = "https://github.com/aontas/XPRising"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"
deca-VampireCommandFramework = "0.9.0"

[build]
icon = "./icon.png"
readme = "./README_TS.md"
outdir = "./build"

[[build.copy]]
source = "./dist/XPRising.dll"
target = "./XPRising.dll"

[[build.copy]]
source = "./dist/CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]