name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          dotnet-quality: 'preview'
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          additionalArguments: '/updateprojectfiles /overrideconfig "mode=Mainline"'

      - name: Build (Release)
        run: dotnet build . --configuration Release --no-restore -p:Version=$GitVersion_SemVer

      - name: GH Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          body: Automatic pre-release of ${{ env.GitVersion_SemVer }} for ${{ env.GitVersion_ShortSha }}
          name: v${{ env.GitVersion_SemVer }}
          fail_on_unmatched_files: true
          prerelease: true
          tag_name: v${{ env.GitVersion_SemVer }}
          files: |
            ./bin/Release/net6.0/XPRising.dll
            LICENSE.txt
            CHANGELOG.md
            icon.png
